name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux (x64)
          - os: macos-latest
            name: macOS (ARM)
          - os: macos-13
            name: macOS (x64)
          - os: windows-latest
            name: Windows (x64)

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest --test-dir build --output-on-failure --timeout 180 -C Release
